apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-plugins
  namespace: vault
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
