---
# TODO: Review how to attach this PVC to the artifactory-values.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-pvc
  namespace: artifactory
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgres-pvc
  namespace: artifactory
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
